Rofi is working with Plasma again

diff --git a/bin/.local/bin/rofi-calc b/bin/.local/bin/rofi-calc
--- a/bin/.local/bin/rofi-calc
+++ b/bin/.local/bin/rofi-calc
@@ -6,7 +6,7 @@
 
 usage() {
     echo "$(tput bold)menu-calc$(tput sgr0)"
-    echo "A calculator for Rofi/dmenu(2)"
+    echo "A calculator for rofi/dmenu(2)"
     echo
     echo "$(tput bold)Usage:$(tput sgr0)"
     echo "    = 4+2"
@@ -15,20 +15,20 @@ usage() {
     echo "    = sqrt(4)"
     echo "    = c(2)"
     echo
-    echo "$(tput bold)Force Rofi/dmenu(2):$(tput sgr0)"
+    echo "$(tput bold)Force rofi/dmenu(2):$(tput sgr0)"
     echo "By default, if rofi exists, it will be used. To force menu-calc to"
     echo "use one or the other, use the --dmenu argument"
     echo
     echo "    = --dmenu=<dmenu_executable>"
     echo
-    echo "$(tput bold)Passing arguments to Rofi/dmenu(2):$(tput sgr0)"
-    echo "Any parameters after ' -- ' will be passed to Rofi/dmenu(2)."
+    echo "$(tput bold)Passing arguments to rofi/dmenu(2):$(tput sgr0)"
+    echo "Any parameters after ' -- ' will be passed to rofi/dmenu(2)."
     echo
-    echo "    = -- <Rofi/dmenu(2) args>"
+    echo "    = -- <rofi/dmenu(2) args>"
     echo
-    echo "The answer can be copied to the clipboard and used for further calculations inside (or outside) Rofi/dmenu."
+    echo "The answer can be copied to the clipboard and used for further calculations inside (or outside) rofi/dmenu."
     echo
-    echo "If launched outside of Rofi/dmenu the expression may need quotation marks."
+    echo "If launched outside of rofi/dmenu the expression may need quotation marks."
     exit
 }
 
@@ -54,7 +54,7 @@ if [ -z "${menu+1}" ]; then
     elif [[ -n $(command -v dmenu) ]]; then
         menu=$(command -v dmenu)
     else
-        echo >&2 "Rofi or dmenu not found"
+        echo >&2 "rofi or dmenu not found"
         exit
     fi
 fi
